apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: chatstreet-backend
  name: chatstreet-backend
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    app: chatstreet-backend
status:
  loadBalancer: {}
