-- MySQL Script generated by MySQL Workbench
-- Fri Jun 16 11:06:51 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `user_id` INT GENERATED ALWAYS AS (),
  `username` VARCHAR(45) NOT NULL,
  `tag` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `recovery_email` VARCHAR(45) NULL COMMENT 'Optional',
  `phone_number` VARCHAR(45) NULL COMMENT 'Optional',
  `birthdate` DATE NULL,
  `registration_timestamp` TIMESTAMP GENERATED ALWAYS AS (CURRENT_TIMESTAMP) VIRTUAL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`violate_codes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`violate_codes` (
  `user_id_fk` INT NOT NULL,
  `password_reset_code` VARCHAR(128) NULL,
  `email_verification_code` VARCHAR(128) NULL,
  PRIMARY KEY (`user_id_fk`),
  INDEX `fk_violate_codes_users_idx` (`user_id_fk` ASC) VISIBLE,
  UNIQUE INDEX `user_fk_UNIQUE` (`user_id_fk` ASC) VISIBLE,
  CONSTRAINT `fk_violate_codes_users`
    FOREIGN KEY (`user_id_fk`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`profiles` (
  `user_id_fk` INT NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `avatar` LONGTEXT NULL,
  `theme` ENUM("DARK", "LIGHT", "SYSTEM") NOT NULL,
  PRIMARY KEY (`user_id_fk`),
  UNIQUE INDEX `user_id_fk_UNIQUE` (`user_id_fk` ASC) VISIBLE,
  CONSTRAINT `fk_table1_users1`
    FOREIGN KEY (`user_id_fk`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`collections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`collections` (
  `collection_id` INT GENERATED ALWAYS AS () VIRTUAL,
  `user_fk` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`collection_id`),
  UNIQUE INDEX `collection_id_UNIQUE` (`collection_id` ASC) VISIBLE,
  INDEX `fk_collections_users1_idx` (`user_fk` ASC) VISIBLE,
  CONSTRAINT `fk_collections_users1`
    FOREIGN KEY (`user_fk`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contacts_lookup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contacts_lookup` (
  `user_id_fk_1` INT NOT NULL,
  `contact_id_fk_2` INT NOT NULL,
  `relationship` ENUM("FRIENDS", "BLOCKED", "INVITED") NOT NULL,
  PRIMARY KEY (`user_id_fk_1`, `contact_id_fk_2`),
  INDEX `fk_users_has_users_users2_idx` (`contact_id_fk_2` ASC) VISIBLE,
  INDEX `fk_users_has_users_users1_idx` (`user_id_fk_1` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_users_users1`
    FOREIGN KEY (`user_id_fk_1`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_users_users2`
    FOREIGN KEY (`contact_id_fk_2`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`collections_contacts_lookup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`collections_contacts_lookup` (
  `collections_id_fk` INT NOT NULL,
  `contacts_lookup_id_fk_1` INT NOT NULL,
  `contacts_lookup_id_fk_2` INT NOT NULL,
  PRIMARY KEY (`collections_id_fk`, `contacts_lookup_id_fk_1`, `contacts_lookup_id_fk_2`),
  INDEX `fk_collections_has_contacts_lookup_contacts_lookup1_idx` (`contacts_lookup_id_fk_1` ASC, `contacts_lookup_id_fk_2` ASC) VISIBLE,
  INDEX `fk_collections_has_contacts_lookup_collections1_idx` (`collections_id_fk` ASC) VISIBLE,
  CONSTRAINT `fk_collections_has_contacts_lookup_collections1`
    FOREIGN KEY (`collections_id_fk`)
    REFERENCES `mydb`.`collections` (`collection_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_collections_has_contacts_lookup_contacts_lookup1`
    FOREIGN KEY (`contacts_lookup_id_fk_1` , `contacts_lookup_id_fk_2`)
    REFERENCES `mydb`.`contacts_lookup` (`user_id_fk_1` , `contact_id_fk_2`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`keys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`keys` (
  `user_id_fk` INT NOT NULL,
  `private_key` TEXT NOT NULL COMMENT 'Salted and Hashed',
  `public_key` TEXT NOT NULL COMMENT 'Salted and Hashed',
  PRIMARY KEY (`user_id_fk`),
  UNIQUE INDEX `user_id_fk_UNIQUE` (`user_id_fk` ASC) VISIBLE,
  CONSTRAINT `fk_keys_users1`
    FOREIGN KEY (`user_id_fk`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`messages` (
  `contacts_lookup_id_fk_1` INT NOT NULL,
  `contacts_lookup_id_fk_2` INT NOT NULL,
  `user_content` LONGTEXT NOT NULL COMMENT 'copy of the contact_content just encrypted with the users own public key.',
  `contact_content` LONGTEXT NOT NULL COMMENT 'message encrypted with the contacts public key.',
  `timestamp` TIMESTAMP GENERATED ALWAYS AS (CURRENT_TIMESTAMP),
  INDEX `fk_messages_contacts_lookup1_idx` (`contacts_lookup_id_fk_1` ASC, `contacts_lookup_id_fk_2` ASC) VISIBLE,
  PRIMARY KEY (`contacts_lookup_id_fk_1`, `contacts_lookup_id_fk_2`),
  CONSTRAINT `fk_messages_contacts_lookup1`
    FOREIGN KEY (`contacts_lookup_id_fk_1` , `contacts_lookup_id_fk_2`)
    REFERENCES `mydb`.`contacts_lookup` (`user_id_fk_1` , `contact_id_fk_2`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
